---
- name: Create Traefik directories
  ansible.builtin.file:
    path: "{{ svc_root }}/{{ item }}"
    state: directory
    recurse: true
  loop:
    - config/traefik
    - data/traefik

- name: Deploy Traefik configuration
  ansible.builtin.template:
    src: traefik.yml.j2
    dest: "{{ svc_root }}/config/traefik/traefik.yml"
    mode: "0644"
