---
vcs_root: /opt/vcs/gitlab-runner

gitlab_url: "https://gitlab.example.com"
gitlab_runner_registration_token: "REGISTRATION_TOKEN"

gitlab_runner_description: "homelab-runner"
gitlab_runner_tags:
  - docker
  - homelab
gitlab_runner_docker_image: "alpine:latest"
