---
vcs_root: /opt/vcs/gitlab-runner

gitlab_url: ""
gitlab_runner_registration_token: ""

gitlab_runner_description: "docker-runner"
gitlab_runner_tags: ["docker"]
gitlab_runner_executor: "docker"
gitlab_runner_docker_image: "docker:latest"

gitlab_runner_config_path: "{{ vcs_root }}/config/config.toml"
