---
- name: Deploy docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ vcs_root }}/docker-compose.yml"
    mode: "0644"

- name: Start GitLab Runner stack
  community.docker.docker_compose:
    project_src: "{{ vcs_root }}"
    state: present
