---
- name: Create directory structure
  ansible.builtin.file:
    path: "{{ svc_root }}/{{ item }}"
    state: directory
    recurse: true
  loop:
    - config/gitlab
    - data/gitlab
    - data/gitlab/logs

- name: Deploy docker-compose definition
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ svc_root }}/docker-compose.yml"
    mode: "0644"

- name: Start GitLab stack
  community.docker.docker_compose:
    project_src: "{{ svc_root }}"
    state: present
