---
- name: Install required packages
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Create directory structure
  ansible.builtin.file:
    path: "{{ vcs_root }}/{{ item }}"
    state: directory
    recurse: true
  loop:
    - config/gitlab
    - data/gitlab
    - data/gitlab/logs

- name: Deploy docker-compose definition
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ vcs_root }}/docker-compose.yml"
    mode: "0644"

- name: Start GitLab stack
  community.docker.docker_compose:
    project_src: "{{ vcs_root }}"
    state: present
